/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'timestamp' : Time,
});
export const JournalEntry = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const Mood = IDL.Variant({
  'bad' : IDL.Null,
  'awful' : IDL.Null,
  'good' : IDL.Null,
  'okay' : IDL.Null,
  'great' : IDL.Null,
});
export const MoodLog = IDL.Record({
  'mood' : Mood,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const UserStats = IDL.Record({
  'riskAlert' : IDL.Bool,
  'totalMoodLogs' : IDL.Nat,
  'totalJournalEntries' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addChatMessage' : IDL.Func(
      [IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }), IDL.Text],
      [],
      [],
    ),
  'checkRiskAlert' : IDL.Func([], [IDL.Bool], ['query']),
  'clearChatHistory' : IDL.Func([], [], []),
  'createJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteJournalEntry' : IDL.Func([Time], [], []),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getLast30DaysMoodLogs' : IDL.Func([], [IDL.Vec(MoodLog)], ['query']),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodLog)], ['query']),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'logMood' : IDL.Func([Mood, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'timestamp' : Time,
  });
  const JournalEntry = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const Mood = IDL.Variant({
    'bad' : IDL.Null,
    'awful' : IDL.Null,
    'good' : IDL.Null,
    'okay' : IDL.Null,
    'great' : IDL.Null,
  });
  const MoodLog = IDL.Record({
    'mood' : Mood,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const UserStats = IDL.Record({
    'riskAlert' : IDL.Bool,
    'totalMoodLogs' : IDL.Nat,
    'totalJournalEntries' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    'addChatMessage' : IDL.Func(
        [IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }), IDL.Text],
        [],
        [],
      ),
    'checkRiskAlert' : IDL.Func([], [IDL.Bool], ['query']),
    'clearChatHistory' : IDL.Func([], [], []),
    'createJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteJournalEntry' : IDL.Func([Time], [], []),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getLast30DaysMoodLogs' : IDL.Func([], [IDL.Vec(MoodLog)], ['query']),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodLog)], ['query']),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'logMood' : IDL.Func([Mood, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };