/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'content' : string,
  'role' : { 'user' : null } |
    { 'assistant' : null },
  'timestamp' : Time,
}
export interface JournalEntry {
  'title' : string,
  'content' : string,
  'timestamp' : Time,
}
export type Mood = { 'bad' : null } |
  { 'awful' : null } |
  { 'good' : null } |
  { 'okay' : null } |
  { 'great' : null };
export interface MoodLog {
  'mood' : Mood,
  'note' : [] | [string],
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserStats {
  'riskAlert' : boolean,
  'totalMoodLogs' : bigint,
  'totalJournalEntries' : bigint,
  'currentStreak' : bigint,
}
export interface _SERVICE {
  'addChatMessage' : ActorMethod<
    [{ 'user' : null } | { 'assistant' : null }, string],
    undefined
  >,
  'checkRiskAlert' : ActorMethod<[], boolean>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'createJournalEntry' : ActorMethod<[string, string], undefined>,
  'deleteJournalEntry' : ActorMethod<[Time], undefined>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getLast30DaysMoodLogs' : ActorMethod<[], Array<MoodLog>>,
  'getMoodHistory' : ActorMethod<[], Array<MoodLog>>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'logMood' : ActorMethod<[Mood, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];